# Giriş 

Soru hücrelerine tıklarken dikkatli olun. <b>Mavi renkli cevab butonuna</b> tıklamayın, aksi halde sorunun cevabı görünecektir, kendinizi biraz zorlayın, hemen cevabı görmeye çalışmayın. Burada gördüğünüz cevaplar benim bulduğum cevaplar olup, sizlerin daha performanslı kodlar yazması muhtemeldir.

Örnek çıktılar bi alttaki hücrede verilmiştir. Bu çıktıları elde etmeye çalışın. (Bu hücreler frozen hücreler olup, bunları silemez veya editleyemezsiniz, o yüzden yeni bir hücre açıp orada çalışın)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss

<h1 style="color:red"> css (Mutlaka çalıştırın)</h1>

Cevapları togglebuttonlar aracılığıyla kolayca görmek için bu sctipti çalıştırıyoruz.

In [2]:
from IPython.display import HTML

HTML('''
<style>
details > summary {
  padding: 4px;
  width: 180px;
  background-color: #eeeeee;
  border: none;
  box-shadow: 1px 1px 2px #bbbbbb;
  cursor: pointer;
  color: blue;
}

details > pre {
  background-color: #eeeeee;
  padding: 4px;
  margin: 0;  
}
</style>''')

# Numpy

## 1-100 arası eşit aralıklı 5 eleman üretin

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
np.linspace(1,100,5)
</pre>
</details>

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

## Numpy dizideki değerleri artırma

Bir dizideki elemanların değerini 1 artırın. dizi: arr=np.array([1,2,3,4,5])

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>  
arr=np.array([1,2,3,4,5])
arr+1
</pre>
</details>

array([2, 3, 4, 5, 6])

## En yüksek frekanslı elemanı bulma

a)Verilen dizideki en çok tekrar eden elemanı ve adedini bulun. `dizi=np.array([10,10,10,20,30,40,40,40,40,50,40,40])`

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
dizi=np.array([10,10,10,20,30,40,40,40,40,50,40,40])
unique, counts = np.unique(dizi, return_counts=True)
maxindex=np.argmax(counts)
maxvalue=counts[maxindex]
item=unique[maxindex]
print(f"{item} elemanından {maxvalue} adet var")
</pre>
</details>

40 elemanından 6 adet var


b)Bu dizideki her bir elemanın frekansını 2 boyutlu bi dizide gösterin

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
np.asarray((unique, counts)).T
</pre>
</details>

array([[10,  3],
       [20,  1],
       [30,  1],
       [40,  6],
       [50,  1]], dtype=int64)

c)bu frekansları bi dictionary olarak gösterin

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
dict(np.asarray((unique, counts)).T)
</pre>
</details>

{10: 3, 20: 1, 30: 1, 40: 6, 50: 1}

## 1-100 arası 5er 5er artan elemanlar üretin

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
np.arange(1,100,5)
</pre>
</details>

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

## linspace v.s arange

İkisi ne zaman eşit sayıda eleman üretir. Bir fonksiyon yazın, bu fonksiyona bi sayı verdiğinizde, linspace ve arange'in aynı değerde eleman üretip üretmediğini bulun

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
def linspacevsarange(n):
    for k in range(1,int(n/2)):
        arr1=np.arange(1,n,k)
        arr2=np.linspace(1,n,k)
        if len(arr1)==len(arr2):
            print(str(k),arr1,arr2)
            break
    else:
        print("bulunamadı")
</pre>
</details>

In [10]:
def linspacevsarange(n):
    ......
        
linspacevsarange(100)        
linspacevsarange(105) #bulamayacak

10 [ 1 11 21 31 41 51 61 71 81 91] [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
bulunamadı


## Kolon seçme

a) 2 boyutlu(10x10) bir diziden 5 indeksli kolonu seçin, ama yine iki boyutlu olsun. dizi:np.arange(100).reshape(10,10)

In [3]:
arr=np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
arr[:,5].reshape(-1,1)
</pre>
</details>

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

b)aynı dizinden 1-3 indeksli kolonları seçin. 

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
idx=np.arange(1,4)
arr[:,idx]
</pre>
</details>

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

c)aynı dizinden 1-3 indeksli kolonlar hariç seçin.

<details>
<summary>Cevabı görmek için tıklayın</summary>
<pre>    
idx=np.delete(np.arange(arr.shape[1]),np.arange(1,4)) #hardcodede 10 değil de dinamk şekilde yazdık
arr[:,idx]
</pre>
</details>

array([[ 0,  4,  5,  6,  7,  8,  9],
       [10, 14, 15, 16, 17, 18, 19],
       [20, 24, 25, 26, 27, 28, 29],
       [30, 34, 35, 36, 37, 38, 39],
       [40, 44, 45, 46, 47, 48, 49],
       [50, 54, 55, 56, 57, 58, 59],
       [60, 64, 65, 66, 67, 68, 69],
       [70, 74, 75, 76, 77, 78, 79],
       [80, 84, 85, 86, 87, 88, 89],
       [90, 94, 95, 96, 97, 98, 99]])

# Pandas

## Datasetler

In [4]:
#1.dataset
dfchurn=pd.read_csv("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Classification/churn.txt")
dfchurn["Churn?"]=dfchurn["Churn?"].map(lambda x:x[:-1])
dfchurn.rename(columns={"Churn?": "Churn"},inplace=True)
dfchurn.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn  
0               1  False  
1               1  False  
2               0  False  
3               2  False  
4               3  False  

[5 rows x 21 columns]

In [5]:
#2.dataset
dfloanchurn=pd.read_csv("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Classification/loan-Churn_Modelling.csv")
dfloanchurn.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
#3.dataset
dfsuperstore=pd.read_excel("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Regression%20TimeSeries/Superstore.xlsx")
dfsuperstore.head()

Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [7]:
#4.dataset
dfCancer=pd.read_csv("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Classification/cancerdata.csv")
dfCancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

## Yeni dataset

### Satır sayısı

<p><a href="https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Di%C4%9Fer/movies.csv">movies</a> datasını import edin ve kaç satırlık data olduğunu söyleyin</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
<pre>
df=pd.read_csv("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Di%C4%9Fer/movies.csv")
len(df)
</pre>
</details>

27278

### Yeni kolon üretme

<p>Title kolonundaki yıl bilgisini alıp başka kolona koyun, ve titledan da çıkarın. Son 5 kaydı gösterin. Bazılarında sonda fazladan boşluk olabilir</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
<pre>

df["Year"]=df.title.apply(lambda x:x.strip()[-5:-1])
df.title=df.title.apply(lambda x:x.strip()[:-7])
df.tail()

</pre>
</details>

movieId                   title                    genres  Year
27273   131254   Kein Bund für's Leben                    Comedy  2007
27274   131256  Feuer, Eis & Dosenbier                    Comedy  2002
27275   131258             The Pirates                 Adventure  2014
27276   131260            Rentun Ruusu        (no genres listed)  2001
27277   131262               Innocence  Adventure|Fantasy|Horror  2014

### Yıl bazlı gruplama

<p>a)Her yıl kaç film çekilmiş, top 5 ve bottom 5 altalta gösterin (bottom 5 için sizi bir süpriz bekleyebilir)<br>
        b)en çok hangi yılda çekilmiş,<br>
        c)bu yılda kaç film çekilmiş. </p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
<pre>
a)
t=df.Year[df.Year.map(lambda x:x.isnumeric())].value_counts().head()
b=df.Year[df.Year.map(lambda x:x.isnumeric())].value_counts().tail()
pd.concat([t,b],axis=0)

b)
df.Year[df.Year.map(lambda x:x.isnumeric())].value_counts().index[0]

c)
df.Year[df.Year.map(lambda x:x.isnumeric())].value_counts()[0]
</pre>
</details>

2009    1113
2012    1022
2011    1016
2013    1011
2008     979
1893       1
1901       1
1903       1
1902       1
1891       1
Name: Year, dtype: int64

'2009'

1113

<h3>Eksik bilgi tespiti</h3>
<p>Kaç filmin yılı bulunmuyor </p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
<pre>
len(df)-len(df.Year[df.Year.map(lambda x:x.isnumeric())])
</pre>
</details>

22

## Churn dataseti

In [8]:
dfchurn.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn  
0               1  False  
1               1  False  
2               0  False  
3               2  False  
4               3  False  

[5 rows x 21 columns]

### Pivot tablo

<p>State ve Churn bazında bir pivot tablo oluşturun</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
dfcross=pd.crosstab(dfchurn["State"],dfchurn["Churn"])
dfcross.head()

#2.yöntem, gereksiz derece uzun
dfcross=dfchurn.pivot_table(values="Account Length", index="State",columns=["Churn"],aggfunc="count") #values yerine herhangi bir kolon olurdu
dfcross.head()
</pre>
</details>

Churn  False  True
State             
AK        49     3
AL        72     8
AR        44    11
AZ        60     4
CA        25     9

### 2.Pivot tablo

<p>Vmail Plan'ları Churn bazında pivotlayın ve elde ettiğiniz dataframe'e True'ların oranını da ekleyin.</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
pivot=dfchurn.groupby(["VMail Plan","Churn"]).size().unstack(level=1)
pivot["TrueRatio"]=pivot["True"]/(pivot["False"]+pivot["True"])
pivot
</pre>
</details>

Churn       False  True  TrueRatio
VMail Plan                        
no           2008   403   0.167151
yes           842    80   0.086768

### barem(bin grup) oluşturma

<p>Numerik kolonları 5'li baremlere ayırın ve bunları ayrı kolon olarak ekleyin, bu kolonlara ait ilk 5 kaydı gösterin.;</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
nums=dfchurn.select_dtypes("number").drop("Area Code",axis=1).columns
for c in nums:
    dfchurn[c+"_discrete"]=pd.cut(dfchurn[c],5)
    dfchurn[c+"_discrete"]=dfchurn[c+"_discrete"].map(lambda x:str(x))
    
dfchurn[[x for x in dfchurn.columns if "discrete" in x]].head()
</pre>
</details>

Account Length_discrete VMail Message_discrete Day Mins_discrete  \
0           (97.8, 146.2]           (20.4, 30.6]  (210.48, 280.64]   
1           (97.8, 146.2]           (20.4, 30.6]  (140.32, 210.48]   
2           (97.8, 146.2]         (-0.051, 10.2]  (210.48, 280.64]   
3            (49.4, 97.8]         (-0.051, 10.2]   (280.64, 350.8]   
4            (49.4, 97.8]         (-0.051, 10.2]  (140.32, 210.48]   

  Day Calls_discrete Day Charge_discrete Eve Mins_discrete Eve Calls_discrete  \
0      (99.0, 132.0]    (35.784, 47.712]  (145.48, 218.22]      (68.0, 102.0]   
1      (99.0, 132.0]    (23.856, 35.784]  (145.48, 218.22]     (102.0, 136.0]   
2      (99.0, 132.0]    (35.784, 47.712]   (72.74, 145.48]     (102.0, 136.0]   
3       (66.0, 99.0]     (47.712, 59.64]   (-0.364, 72.74]      (68.0, 102.0]   
4      (99.0, 132.0]    (23.856, 35.784]  (145.48, 218.22]     (102.0, 136.0]   

  Eve Charge_discrete Night Mins_discrete Night Calls_discrete  \
0    (12.364, 18.546]    (171.92, 246.28]        (89.8, 118.2]   
1    (12.364, 18.546]    (246.28, 320.64]        (89.8, 118.2]   
2     (6.182, 12.364]     (97.56, 171.92]        (89.8, 118.2]   
3    (-0.0309, 6.182]    (171.92, 246.28]         (61.4, 89.8]   
4    (12.364, 18.546]    (171.92, 246.28]       (118.2, 146.6]   

  Night Charge_discrete Intl Mins_discrete Intl Calls_discrete  \
0       (7.732, 11.078]        (8.0, 12.0]        (-0.02, 4.0]   
1      (11.078, 14.424]       (12.0, 16.0]        (-0.02, 4.0]   
2        (4.386, 7.732]       (12.0, 16.0]          (4.0, 8.0]   
3       (7.732, 11.078]         (4.0, 8.0]          (4.0, 8.0]   
4       (7.732, 11.078]        (8.0, 12.0]        (-0.02, 4.0]   

  Intl Charge_discrete CustServ Calls_discrete  
0         (2.16, 3.24]           (-0.009, 1.8]  
1         (3.24, 4.32]           (-0.009, 1.8]  
2         (3.24, 4.32]           (-0.009, 1.8]  
3         (1.08, 2.16]              (1.8, 3.6]  
4         (2.16, 3.24]              (1.8, 3.6]

## Loanchurn dataset

In [9]:
dfloanchurn.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

### Barem(bin grup) oluşturma

<p>Geography bazında ortalama değerleri hesaplayıp bi kolona basın, exceldeki Averageif gibi, ancak küsuratları kaldırın ve binlik ayraç ekleyin. Bir de yaşları 5 gruba ayırın:["Very young", "Young", "MiddleAge","Old","Very Old"]. Son olarak ["Age","Geography","GeographyMeanBalance","Age_group"] kolonları için random 10 kayıt gösterin.</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
from math import trunc
import locale as lc
lc.setlocale(lc.LC_ALL, 'tr_tr')
dfloanchurn["GeographyMeanBalance"]=dfloanchurn.groupby("Geography")["Balance"].transform("mean").map(lambda x: trunc(x)).map(lambda x: lc.format_string("%.0f",x,True))

dfloanchurn["Age_group"]=pd.cut(dfloanchurn["Age"], 5,labels=["Very young", "Young", "MiddleAge","Old","Very Old"])
dfloanchurn[["Age","Geography","GeographyMeanBalance","Age_group"]].sample(10)
</pre>
</details>

'tr_tr'

Age Geography GeographyMeanBalance   Age_group
4057   26    France               62.092  Very young
3081   29    France               62.092  Very young
5814   40   Germany              119.730       Young
7080   51   Germany              119.730   MiddleAge
3121   27   Germany              119.730  Very young
2619   49     Spain               61.818   MiddleAge
7925   33     Spain               61.818       Young
1626   28    France               62.092  Very young
2440   59     Spain               61.818   MiddleAge
8148   47     Spain               61.818       Young

## Superstore dataseti

In [10]:
dfsuperstore.head()

Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

### Özel permutasyon

<p>Numerik kolonların başlıkları için permütasyon listesi oluşturun. Ama içinde "co" geçenler olmasın(case insensitive). (NOT: Normalde itertoolstan yaralanarak list(permutations(kolonlistesi,2)) şeklinde alabilirdik. Ama içinde "co" geçmeyenler için istediğimiz için bunu kullanamayız(mı acaba, belki de kullanabiliriz, deneyin bakalım)</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
nums=dfsuperstore.select_dtypes("number").columns
for c1 in nums:
    for c2 in nums:
        if c1 != c2 and "co" not in c1.lower() and "co" not in c2.lower():
            print((c1,c2))
</pre>
</details>

('Row ID', 'Sales')
('Row ID', 'Quantity')
('Row ID', 'Profit')
('Sales', 'Row ID')
('Sales', 'Quantity')
('Sales', 'Profit')
('Quantity', 'Row ID')
('Quantity', 'Sales')
('Quantity', 'Profit')
('Profit', 'Row ID')
('Profit', 'Sales')
('Profit', 'Quantity')


### Özel korelasyon

<p>Numerik kolonlar için bir korelasyon matrisi çıkarın. Ancak bu liste alfabetik olsun, hem kolonda hem satırda. Ancak target kolonu(Pofit) en sonda yer alsın. </p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
target="Profit"
sortedcorr=dfsuperstore.corr().sort_index().sort_index(axis=1)        
cols = [col for col in sortedcorr if col != target] + [target]
sortedcorr = sortedcorr[cols]
new_index = [i for i in sortedcorr.index if i != target] + [target]
sortedcorr=sortedcorr.reindex(new_index)
sortedcorr
</pre>
</details>

Discount  Postal Code  Quantity    Row ID     Sales    Profit
Discount     1.000000     0.058443  0.008623  0.013480 -0.028190 -0.219487
Postal Code  0.058443     1.000000  0.012761  0.009671 -0.023854 -0.029961
Quantity     0.008623     0.012761  1.000000 -0.004016  0.200795  0.066253
Row ID       0.013480     0.009671 -0.004016  1.000000 -0.001359  0.012497
Sales       -0.028190    -0.023854  0.200795 -0.001359  1.000000  0.479064
Profit      -0.219487    -0.029961  0.066253  0.012497  0.479064  1.000000

### özel korelasyon2

<p>Korelasyon değeri +/-%20nin üzerinde olan çiftleri bir dataframede gösterin.</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
nums=dfsuperstore.select_dtypes("number").columns
temp=[]
final=[]
for n1 in nums:
    for n2 in nums:        
        corr=np.corrcoef(dfsuperstore[n1],dfsuperstore[n2])[0][1]        
        if n1 != n2 and abs(corr)>0.2 and sorted([n1,n2]) not in temp:            
            temp.append(sorted([n1,n2]))
            final.append((n1,n2,corr))
            
pd.DataFrame(final,columns=["İlk","İkinci","Corr"])            
</pre>
</details>


İlk    İkinci      Corr
0     Sales  Quantity  0.200795
1     Sales    Profit  0.479064
2  Discount    Profit -0.219487

### Yıl bazında gruplama

<p>Yıllık satışları gösterin</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
dfsuperstore.groupby("Order Date")["Sales"].sum().resample('Y').sum()          

#veya
dfsuperstore.set_index("Order Date").resample('Y')["Sales"].sum() 
</pre>
</details>


Order Date
2014-12-31    484247.4981
2015-12-31    470532.5090
2016-12-31    609205.5980
2017-12-31    733215.2552
Freq: A-DEC, Name: Sales, dtype: float64

### Ay bazında gruplama

<p>2015 aylık satışları gösterin</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
datesales=dfsuperstore.groupby("Order Date")["Sales"].sum().resample('M').sum()
datesales=datesales[datesales.index.year==2015]
datesales.index=datesales.index.month
datesales.index.name="Ay"
datesales
</pre>
</details>


In [17]:
#çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


Ay
1     18174.0756
2     11951.4110
3     38726.2520
4     34195.2085
5     30131.6865
6     24797.2920
7     28765.3250
8     36898.3322
9     64595.9180
10    31404.9235
11    75972.5635
12    74919.5212
Name: Sales, dtype: float64

### Pivot

<p>Bölgelerin yıllık satışlarını gösterin, küsuratları kaldırın ve binlik ayraç ekleyin</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
from math import trunc
import locale as lc
lc.setlocale(lc.LC_ALL, 'tr_tr')

dfregionsale=pd.crosstab(dfsuperstore["Order Date"], dfsuperstore["Region"],values=dfsuperstore["Sales"],aggfunc="sum").resample("Y").sum()
dfregionsale.index=dfregionsale.index.year
dfregionsale.index.name="Yıl"
dfregionsale=dfregionsale.applymap(lambda x: trunc(x))
dfregionsale.applymap(lambda x: lc.format_string("%.0f",x,True))
</pre>
</details>

In [11]:
#çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


## Cancer dataseti

In [12]:
dfCancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

### index değiştirme

<p>id kolonunu index yapın ve head alın.</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
dfCancer.set_index("id",drop=True,inplace=True) #burda sadece kolon adını yamzanız gerekiyor, dfCancer["idf"] değil 
dfCancer.head()
</pre>
</details>

In [15]:
#çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                         
842302           M        17.99         10.38          122.80     1001.0   
842517           M        20.57         17.77          132.90     1326.0   
84300903         M        19.69         21.25          130.00     1203.0   
84348301         M        11.42         20.38           77.58      386.1   
84358402         M        20.29         14.34          135.10     1297.0   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
842302            0.11840           0.27760          0.3001   
842517            0.08474           0.07864          0.0869   
84300903          0.10960           0.15990          0.1974   
84348301          0.14250           0.28390          0.2414   
84358402          0.10030           0.13280          0.1980   

          concave points_mean  symmetry_mean  ...  texture_worst  \
id                                            ...                  
842302                0.14710         0.2419  ...          17.33   
842517                0.07017         0.1812  ...          23.41   
84300903              0.12790         0.2069  ...          25.53   
84348301              0.10520         0.2597  ...          26.50   
84358402              0.10430         0.1809  ...          16.67   

          perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
id                                                                           
842302             184.60      2019.0            0.1622             0.6656   
842517             158.80      1956.0            0.1238             0.1866   
84300903           152.50      1709.0            0.1444             0.4245   
84348301            98.87       567.7            0.2098             0.8663   
84358402           152.20      1575.0            0.1374             0.2050   

          concavity_worst  concave points_worst  symmetry_worst  \
id                                                                
842302             0.7119                0.2654          0.4601   
842517             0.2416                0.1860          0.2750   
84300903           0.4504                0.2430          0.3613   
84348301           0.6869                0.2575          0.6638   
84358402           0.4000                0.1625          0.2364   

          fractal_dimension_worst  Unnamed: 32  
id                                              
842302                    0.11890          NaN  
842517                    0.08902          NaN  
84300903                  0.08758          NaN  
84348301                  0.17300          NaN  
84358402                  0.07678          NaN  

[5 rows x 32 columns]

### numerik kolonları birleştirme

<p>raidus_mean ve texture_mean kolonlarını aralarında - işareti olacak şekilde birleştirin. Yeni kolonun adı "ikili" olsun. Ve sadece bu 3 kolonu gösterin.</p>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
dfCancer["ikili"]=dfCancer.radius_mean.astype(str)+"-"+dfCancer.texture_mean.astype(str)
dfCancer[["radius_mean","texture_mean","ikili"]].head()
</pre>
</details>

In [14]:
#çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


### null analizi

<p>Sırayla şunları bulun.</p>
<pre>
1- En az 1 null hücre içieren kaç kolon var?
2- Bu kolonlar hangileri?
3- Tamamı null hücre olan kaç kolon var?
4- Bu kolonlar hangileri?
5- En az 1 null kolon içeren kaç satır var?
6- bu satırlardan rasgele birini gösterin
</pre>
<br>

<details><summary>Cevabı görmek için tıklayın</summary>
    
<pre>
1-dfCancer.isnull().any().sum()
2-dfCancer.columns[dfCancer.isnull().any().values==True]
3-dfCancer.isnull().all().sum()
4-dfCancer.columns[dfCancer.isnull().all().values==True]
5-dfCancer.isnull().any(axis=1).sum()
6-dfCancer.loc[dfCancer.isnull().any(axis=1)].sample()
</pre>
</details>

In [40]:
#1-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


1

In [42]:
#2-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


Index(['Unnamed: 32'], dtype='object')

In [43]:
#3-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


1

In [45]:
#4-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


Index(['Unnamed: 32'], dtype='object')

In [46]:
#5-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


569

In [52]:
#6-çözümünüzü burada geliştirin. Çıktı, aşağıdaki gibi olmalı


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                         
90769602         B        12.72         17.67           80.98      501.3   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
90769602          0.07896           0.04522         0.01402   

          concave points_mean  symmetry_mean  ...  perimeter_worst  \
id                                            ...                    
90769602              0.01835         0.1459  ...            88.87   

          area_worst  smoothness_worst  compactness_worst  concavity_worst  \
id                                                                           
90769602       586.8            0.1068            0.09605          0.03469   

          concave points_worst  symmetry_worst  fractal_dimension_worst  \
id                                                                        
90769602               0.03612          0.2165                  0.06025   

          Unnamed: 32        ikili  
id                                  
90769602          NaN  12.72-17.67  

[1 rows x 33 columns]

# Başka Alıştırma Kaynakları

Bunlar hem yararlandığım kaynaklar olup hem de sizin ekstra pratik yapabilecğeiniz kaynaklardır.

- https://github.com/guipsamora/pandas_exercises
- https://www.machinelearningplus.com/python/101-pandas-exercises-python/
- https://www.w3resource.com/python-exercises/numpy/index.php
- https://www.w3resource.com/python-exercises/pandas/index.php